#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#

#
# ./run all tape tests
#
echo "Start autochanger tests"
echo "Start autochanger tests" >>test.out
rm -f dumps/*

./run tests/incremental-changer
./run tests/two-pool-changer
./run tests/two-volume-changer
./run tests/vol-duration-changer

echo "End autochanger tests"
echo "End autochanger tests" >>test.out
