#!/bin/sh
#
# Copyright (C) 2000-2017 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# ./run all changer tests
#

if test x$FORCE_CLOUD = xyes ; then
   echo "All changer tests skipped for FORCE_CLOUD"
   exit 0
fi

echo "Start autochanger tests"
echo "Start autochanger tests" >>test.out
rm -f dumps/*

./run tests/incremental-changer
./run tests/two-pool-changer
./run tests/two-volume-changer
./run tests/vol-duration-changer

echo "End autochanger tests"
echo "End autochanger tests" >>test.out
