#!/bin/sh
#
# Copyright (C) 2000-2017 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# ./run all tape tests
#
. ./config

# 
# If we have an autoloader, load the tape in slot1
if test ! x$AUTOCHANGER = x/dev/null ; then
   a=`bin/mtx-changer $AUTOCHANGER loaded $SLOT1 $TAPE_DRIVE $DRIVE1`
   if test $a -eq 0 ; then
      bin/mtx-changer $AUTOCHANGER load $SLOT1 $TAPE_DRIVE $DRIVE1
   fi
fi
echo " "
echo " " >>test.out
if test x$FORCE_DEDUP = xyes ; then
   echo "All tape tests skipped for FORCE_DEDUP"
   exit 0
fi
if test x$FORCE_ALIGNED = xyes ; then
   echo "All tape tests skipped for FORCE_ALIGNED"
   exit 0
fi
if test x$FORCE_CLOUD = xyes ; then
   echo "All tape tests skipped for FORCE_CLOUD"
   exit 0
fi
echo "Start all non-root tape tests"
echo "Start all non-root tape tests" >>test.out
rm -f dumps/*
./run tests/ansi-label-tape
./run tests/backup-bacula-tape
./run tests/bscan-tape
./run tests/fixed-block-size-tape
./run tests/four-concurrent-jobs-tape
./run tests/four-jobs-tape
./run tests/incremental-tape
./run tests/relabel-tape
./run tests/restore-by-file-tape
./run tests/small-file-size-tape
./run tests/truncate-bug-tape
./run tests/verify-vol-tape
# ./run tests/manual-two-vol-tape
echo "End all non-root tape tests"
echo "End all non-root tape tests" >>test.out
