#!/bin/sh
#
# Copyright (C) 2000-2017 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# ./run all tests
#
echo " "
echo " " >>test.out
echo "Start non-root disk tests"
echo "Start non-root disk tests" >>test.out
rm -f dumps/*
./run tests/acl-xattr-test
#./run tests/aligned-bug-8013-test
./run tests/allowcompress-test
./run tests/auto-label-many-test
./run tests/auto-label-test
./run tests/accurate-test
./run tests/backup-bacula-test
./run tests/backup-to-null
./run tests/base-job-test
#
# console-acl-test is broken and has
#  orphaned buffers
#./run tests/console-acl-test
#
./run tests/bconsole-test
./run tests/bextract-test
./run tests/big-vol-test
#./run tests/bpipe-test  -- errors
./run tests/broken-media-bug-2-test
./run tests/bscan-test
./run tests/btape-test
./run tests/bsr-opt-test
./run tests/console-dotcmd-test
./run tests/cancel-multiple-test
./run tests/comment-test
./run tests/compressed-test
./run tests/compress-encrypt-test
./run tests/concurrent-jobs-test
./run tests/copy-jobspan-label-wait-test
./run tests/copy-jobspan-test
./run tests/copy-job-test
./run tests/copy-uncopied-test
./run tests/copy-upgrade-test
./run tests/copy-volume-test
#./run tests/crazy-smaller-vol-test
./run tests/data-encrypt-test
#./run tests/aligned-test
./run tests/delete-test
./run tests/differential-test
./run tests/encrypt-bug-test
./run tests/estimate-test
./run tests/exclude-dir-test
./run tests/fifo-test
./run tests/fileregexp-test
./run tests/four-concurrent-jobs-test
./run tests/four-jobs-test
./run tests/hardlink-test
./run tests/incremental-test
./run tests/jobmedia-bug-test
./run tests/lzo-encrypt-test
./run tests/lzo-test
./run tests/many-reload-test
./run tests/max-vol-jobs-test
./run tests/maxbw-test
./run tests/maxbytes-test
./run tests/maxtime-test
./run tests/maxuseduration-test
./run tests/maxvol2-test
./run tests/maxvol-test
./run tests/messages-test
./run tests/messages-saved-test
./run tests/migration-job-no-resource-test
./run tests/migration-job-purge-test
./run tests/migration-jobspan-test
./run tests/migration-job-test
./run tests/migration-time-test
./run tests/migration-volume-test
./run tests/multi-storage-test
./run tests/next-pool-test
./run tests/next-vol-test
./run tests/next-vol-bug-7302
./run tests/poll-interval-test
./run tests/pool-attributes-test
./run tests/prune-base-job-test
./run tests/prune-copy-test
./run tests/prune-migration-test
./run tests/prune-pool-test
./run tests/prune-test
./run tests/query-test
./run tests/recycle-test
./run tests/regexwhere-test
./run tests/restart2-base-job-test
./run tests/restart2-job-test
./run tests/restart-accurate-job-test
./run tests/restart-job-test
./run tests/restart-jobmedia-test
./run tests/restart-sd-test
./run tests/restart-reschedule-test
./run tests/restore2-by-file-test
./run tests/restore-by-file-test
./run tests/restore-disk-seek-test
./run tests/restore-stop-read-test
./run tests/restore-stop-read2-test
./run tests/restore-multi-session-test
#./run tests/remote-console-test
./run tests/runscript-test
./run tests/sd-sd-test
./run tests/six-vol-test
./run tests/source-addr-test
./run tests/span-vol-test
./run tests/sparse-compressed-test
./run tests/sparse-lzo-test
./run tests/sparse-test
./run tests/stats-test
./run tests/strip-test
./run tests/stop-restart-test
./run tests/tls-duplicate-job-test
./run tests/tls-test
./run tests/truncate-test
./run tests/truncate2-test
./run tests/two-jobs-test
./run tests/two-vol-test
./run tests/verify-data-test
./run tests/verify-cat-test
./run tests/verify-vol-test
./run tests/verify-voltocat-test
./run tests/virtual-backup-test
./run tests/virtual-backup2-test
./run tests/virtual-changer-test
./run tests/virtual-jobid-test
./run tests/virtualfull-bug-7154
./run tests/weird-files2-test
./run tests/weird-files-test
./run tests/2media-virtual-test
#./run tests/priority-test # broken
echo "End non-root disk tests"
echo "End non-root disk tests" >>test.out

# 
# The following are Virtual Disk Autochanger tests
echo " "
echo " " >>test.out
echo "Start non-root virtual disk autochanger tests"
echo "Start non-root virtual disk autochanger tests" >>test.out
#./run tests/three-pool-recycle-test
./run tests/three-pool-virtual-test
./run tests/two-pool-test
./run tests/fast-two-pool-test
./run tests/two-volume-test
./run tests/incremental-2disk
./run tests/2drive-incremental-2disk
./run tests/scratch-pool-test
./run tests/scratchpool-pool-test
./run tests/2drive-concurrent-test
./run tests/incremental-2media
./run tests/three-pool-test
./run tests/2drive-3pool-test
./run tests/2drive-swap-test
echo "End non-root virtual disk autochanger tests"
echo "End non-root virtual disk autochanger tests" >>test.out
