#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#

#
# Run all root tests
#
echo " "
echo " " >>test.out
echo "Start root tests"
echo "Start root tests" >>test.out
rm -f dumps/*
./run tests/dev-test-root
./run tests/etc-test-root
./run tests/lib-test-root
./run tests/usr-tape-root
echo "End root ./run tests"
echo "End root ./run tests" >>test.out
