#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#

#
# test only the disk based regression scripts
#
# Include full output
LANG=C
echo "Begin nightly-tape `date`"
REGRESS_DEBUG=1
export REGRESS_DEBUG
rm -rf Testing
rm -f dumps/*
git pull
make distclean
scripts/config_dart
nice ctest -D Nightly -R "^tape:"
rtn=$?
i=0
while [ $i -le 5 ]; do
   if [ $rtn = 0 ] || [ "$rtn" = "8" ]; then
      break;
   fi
   echo "Submit failed, waiting 5 mins"
   sleep 300
   echo "ctest failed re-running Submit"
   ctest -D NightlySubmit
   rtn=$?
   i=`expr $i + 1`
done
echo "End nightly-tape `date`"
