#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#

#
# Script to run a regression test with a time limit (in seconds)
#  this allows the script to be killed if say the SD crashes
#  due to an ASSERT.  Otherwise the script will hang for
#  a very long time, perhaps forever.
# Of course, this implies that all tests must terminate normally
#  within the timeout period (900 seconds).
#
if [ -f bin/timelimit ] ; then
   WARNTIME=900 KILLTIME=50 bin/timelimit $*
   if [ $? != 0 ] ; then
      echo " "
      echo "=== Test $* failed ==="
      echo " "
      echo " " >>test.out
      echo "=== Test $* failed ===" >>test.out
      echo " " >>test.out
      exit 1
   fi
else
   nice $*
fi
#echo " "
#echo " "
#grep -e" \!\!\!\!" -e"===\ Test" test.out
