#!/usr/bin/env python
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
from time import time as now 

fn = open('time.out', 'w+')
fn.write('%s' % now())
fn.close()
