#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# This is an alist unit test
#
. scripts/regress-utils.sh
do_regress_unittest "alist_test" "src/lib"
