#!/bin/sh
#
# Copyright (C) 2000-2018 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# This is an open_bpipe() unit test
#
TestName="bpipe_test"
. scripts/functions
make -C $src/src/tools install-unittests

$bin/$TestName
exit $?
