#!/bin/sh
#
# Copyright (C) 2000-2018 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# This is an breaddir() unit test
#
TestName="breaddir_test"
. scripts/functions
make -C $src/src/tools install-unittests

$bin/$TestName
exit $?
