#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# Radosław Korzeniewski, MMXVIII
# radoslaw@korzeniewski.net, radekk@inteos.pl
# Inteos Sp. z o.o. http://www.inteos.pl/
#
# This is an ConfigFile/ini unit test
#
TestName="collect_test"
. scripts/functions
make -C $src/src/lib $TestName

$src/src/lib/$TestName
exit $?
