#!/bin/sh
#
# Copyright (C) 2000-2020 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#

#
# Attempt to backup and restore a file with the bpipe plugin
#
TestName="debug-test"
JobName=pluginTest
. scripts/functions

scripts/cleanup
scripts/copy-plugin-confs
echo "${cwd}/build/po" >${cwd}/tmp/file-list
rm -f ${cwd}/working/*trace*

start_test

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@output /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=File1 volume=TestVolume001
update volume=TestVolume001 MaxVolBytes=1000
run job=$JobName storage=File1 yes
@sleep 5
messages
quit
END_OF_DATA

run_bacula

killall -SEGV bacula-dir bacula-sd bacula-fd

test -f working/*dir*lockdump
dstat=$?
test -f working/*fd*lockdump
dstat=`expr $dstat + $?`
test -f working/*sd*lockdump
dstat=`expr $dstat + $?`
test -f working/*dir*traceback
dstat=`expr $dstat + $?`
test -f working/*fd*traceback
dstat=`expr $dstat + $?`
test -f working/*sd*traceback
dstat=`expr $dstat + $?`

grep $JobName working/*dir*lockdump > /dev/null 2>&1
dstat=`expr $dstat + $?`
grep bpipe-fd.so working/*fd*lockdump > /dev/null 2>&1
dstat=`expr $dstat + $?`
grep $JobName working/*fd*lockdump > /dev/null 2>&1
dstat=`expr $dstat + $?`

bstat=0
rstat=0

stop_bacula

end_test
