#!/bin/sh
#
# Copyright (C) 2000-2017 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# Run a simple backup of a big file but 
#   split the archive into four volumes, two of which are
#   totally full. I.e. make sure that bsr selects all tapes 
#   including those fully spanned.
#
TestName="file-span-vol-test"
JobName=SpanVol
. scripts/functions

scripts/cleanup
scripts/copy-test-confs
rm -f $cwd/build/big

dd if=/dev/zero of=$tmp/big count=10000 > /dev/null

echo "$tmp/big" >${cwd}/tmp/file-list
echo "${cwd}/build" >>${cwd}/tmp/file-list
change_jobname NightlySave $JobName
start_test

# Remove last / and convert all / to cd commands
CD=`printf $tmp | sed 's:/$::' | sed 's:/:\ncd :g'`
echo "CD=${CD}"

cat <<END_OF_DATA >${cwd}/tmp/bconcmds
@output /dev/null
messages
@$out ${cwd}/tmp/log1.out
label storage=File1 volume=TestVolume004
label storage=File1 volume=TestVolume003
label storage=File1 volume=TestVolume002
label storage=File1 volume=TestVolume001
update Volume=TestVolume004 MaxVolBytes=3000000
update Volume=TestVolume003 MaxVolBytes=3000000
update Volume=TestVolume002 MaxVolBytes=3000000
run job=$JobName fileset=SimpleSet storage=File1 yes
wait
list volumes
messages
@# 
@# now do a restore
@#
@$out ${cwd}/tmp/log2.out
restore where=$tmp/bacula-restores select storage=File1
unmark *
${CD}
mark big
done
yes
wait
messages
quit
END_OF_DATA

run_bacula
check_for_zombie_jobs storage=File1
stop_bacula

check_two_logs

diff -q $tmp/big $tmp/bacula-restores/$tmp/big
if [ $? -ne 0 ]; then
    print_debug "ERROR: $tmp/big $tmp/bacula-restores/$tmp/big are different"
    print_debug `ls -l $tmp/big $tmp/bacula-restores/$tmp/big are different`
    rstat=1
fi

end_test
