#!/bin/sh

set -e

if [ "$1" = "remove" ]
then
	[ ! -e /usr/share/baculum/htdocs/protected/API/Config/api.conf ] ||
		mv /usr/share/baculum/htdocs/protected/API/Config/api.conf \
		/usr/share/baculum/htdocs/protected/API/Config/api.conf.apache
	# remove debug files if any
	[ ! -e /usr/share/baculum/htdocs/protected/API/Logs/baculum-api.log ] ||
		rm /usr/share/baculum/htdocs/protected/API/Logs/baculum-api*.log
fi

#DEBHELPER#

exit 0
