#!/bin/sh

set -e

if [ "$1" = "remove" ]
then
	[ ! -e /usr/share/baculum/htdocs/protected/API/Config/api.conf ] ||
		mv /usr/share/baculum/htdocs/protected/API/Config/api.conf \
		/usr/share/baculum/htdocs/protected/API/Config/api.conf.lighttpd
	# remove debug files if any
	[ ! -e /usr/share/baculum/htdocs/protected/API/Config/baculum-api.dbg ] ||
		rm /usr/share/baculum/htdocs/protected/API/Config/baculum-api*.dbg
fi

#DEBHELPER#

exit 0
