#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
# Upload to File Release System on serfullver
#
. ./config

ver="7.2.0"
fullver="bacula-7.2.0"
RSYNC="rsync -av --no-g --progress $upload_opt"

do_upload()
{
where=$1
echo "Creating ${where}:/var/www/bacula/downloads/$fullver"
ssh ${where} <<EOF
cd /var/www/bacula/downloads/
mkdir -p $fullver
EOF

echo "Uploading source"
for i in bacula-*-$ver*; do \
   echo "Uplod $i to ${where}:/var/www/bacula/downloads/$fullver"
   $RSYNC $i ${where}:/var/www/bacula/downloads/$fullver/; \
done

# Upload release notes
echo "Uplod ReleaseNote to ${where}:/var/www/bacula/downloads/$fullver"
$RSYNC ReleaseNotes ${where}:/var/www/bacula/downloads/$fullver/
echo "Uplod ChangeLog to ${where}:/var/www/bacula/downloads/$fullver"
$RSYNC ChangeLog ${where}:/var/www/bacula/downloads/$fullver/


}

do_upload bacula
