#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#

cp -f scripts/new-test-bacula-dir.conf ${conf}/bacula-dir.conf
cp -f scripts/test-bacula-sd.conf ${conf}/bacula-sd.conf
cp -f scripts/crypto-bacula-fd.conf ${conf}/bacula-fd.conf
cp -f scripts/test-console.conf ${conf}/bconsole.conf
cp -f scripts/test-console.conf ${conf}/bat.conf
cp -f scripts/cryptokeypair.pem ${conf}/cryptokeypair.pem
cp -f scripts/master2048.cert ${conf}/master2048.cert
