#!/bin/sh
#
# Copyright (C) 2000-2020 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#

cp -f scripts/bacula-dir-fifo.conf ${conf}/bacula-dir.conf
cp -f scripts/bacula-sd-fifo.conf ${conf}/bacula-sd.conf
cp -f scripts/test-bacula-fd.conf ${conf}/bacula-fd.conf
cp -f scripts/test-console.conf ${conf}/bconsole.conf
cp -f scripts/test-console.conf ${conf}/bat.conf

scripts/set_tape_options
