#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#

cp -f ${rscripts}/new-test-bacula-dir.conf ${conf}/bacula-dir.conf
cp -f ${rscripts}/test-bacula-sd.conf ${conf}/bacula-sd.conf
cp -f ${rscripts}/test-bacula-fd.conf ${conf}/bacula-fd.conf
cp -f ${rscripts}/test-console.conf ${conf}/bconsole.conf
cp -f ${rscripts}/test-console.conf ${conf}/bat.conf

${rscripts}/set_tape_options
