#!/bin/sh
#
# Copyright (C) 2000-2015 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#

#
# Setup for using the Virtual Disk Changer (simulates tape changer)
#
cp -f scripts/bacula-dir-virtual.conf ${conf}/bacula-dir.conf
cp -f scripts/bacula-sd-virtual.conf ${conf}/bacula-sd.conf
cp -f scripts/test-bacula-fd.conf ${conf}/bacula-fd.conf
cp -f scripts/test-console.conf ${conf}/bconsole.conf
cp -f scripts/test-console.conf ${conf}/bat.conf
