#!/bin/sh
#
# Copyright (C) 2000-2017 Kern Sibbald
# License: BSD 2-Clause; see file LICENSE-FOSS
#
/bin/cp -f ${rscripts}/bacula-dir-tape.conf ${conf}/bacula-dir.conf
/bin/cp -f ${rscripts}/bacula-sd-btape.conf ${conf}/bacula-sd.conf
/bin/cp -f ${rscripts}/test-bacula-fd.conf ${conf}/bacula-fd.conf
/bin/cp -f ${rscripts}/test-console.conf ${conf}/bconsole.conf
/bin/cp -f ${rscripts}/test-console.conf ${conf}/bat.conf

${rscripts}/set_tape_options
